# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20170722_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='professor',
            field=models.ManyToManyField(related_name='Detail', to='student.professor'),
        ),
        migrations.AddField(
            model_name='details',
            name='subject',
            field=models.ManyToManyField(related_name='Detail', to='student.Subject'),
        ),
    ]
