# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20171013_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='professor',
            field=models.ManyToManyField(related_name='Detail', to='student.Professor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
