# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20171013_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='details',
            name='professor',
            field=models.ManyToManyField(related_name='Detail', to='student.Professor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
