# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20171014_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='professor',
            field=models.ManyToManyField(related_name='Detail', to='student.Professor'),
        ),
    ]
